builders:
  matches_builder:
   import: 'package:cheer_for_your_hometown_jp/matches_builder.dart'
   builder_factories: ['myFootballMatchesBuilderFactory']
   build_extensions: {'.csv': ['.g.dart']}
   auto_apply: root_package
   build_to: source
  stadiums_builder:
   import: 'package:cheer_for_your_hometown_jp/stadiums_builder.dart'
   builder_factories: ['myStadiumsBuilderFactory']
   build_extensions: {'.csv': ['.g.dart']}
   auto_apply: root_package
   build_to: source
targets:
  $default:
    builders:
      cheer_for_your_hometown_jp:matches_builder:
        generate_for:
          include:
            - lib/matches_*.csv
      cheer_for_your_hometown_jp:stadiums_builder:
        generate_for:
          include:
            - lib/stadiums.csv
